class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        for ch in set(t):
            if t.count(ch) != s.count(ch):
                return ch

            





# 0
# 0Streaks
# Ready to Practice?
# DCC Badge

# avatar
# Avatar
# SiddhiDoiphode
# Access all features with our Premium subscription!
# myLists
# My Lists
# notebook
# Notebook
# submissions
# Submissions
# progress
# Progress
# points
# Points
# Try New Features
# Orders
# My Playgrounds
# Settings
# Appearance
# Sign Out
# Premium
# Description
# Accepted
# Accepted
# Editorial
# Editorial
# Solutions
# Solutions
# Submissions
# Submissions
# Code
# Testcase
# Testcase
# Test Result
# 389. Find the Difference
# Solved
# Easy
# Topics
# premium lock icon
# Companies
# You are given two strings s and t.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Return the letter that was added to t.

 

# Example 1:

# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
# Example 2:

# Input: s = "", t = "y"
# Output: "y"
 

# Constraints:

# 0 <= s.length <= 1000
# t.length == s.length + 1
# s and t consist of lowercase Eng